### ISSUE TITLE
finish fixing box-drawing (block and shade) glyph gaps and add more glyphs

### ISSUE THREAD

**Issue by blobject** [agarick/agave#14]
1. try overshooting by 64 only
1. decide whether to overshoot shade (test on different programs)
1. add u256d-u257f
1. add sample that utilises all the box-drawing glyphs

**Comment by blobject** [comment]
Fixed in https://github.com/agarick/agave/commit/b7e7af9d800c513c68e1feb8e7b96d813a34102e and closing.

**In response to first comment:**

1. Tried reducing (box-drawing glyphs') overshoots of 128 down to 64, and things still look okay. So 64 it is.
1. Decided to stretch the top of shading glyphs by 256, to reflect the [new ascent metrics](https://github.com/agarick/agave/releases/tag/v16).
    - But decided not to overshoot even further by 64. Thus, gaps will appear between shading glyphs. But strict continuity between shading glyphs has been deemed to not be so crucial, as other factors in rendering will make things look imperfect anyway, and it is hard to standardise behavior across sizes and platforms.
    - This may change in the future upon learning why the rendering is imperfect.
1. Added more box-drawing glyphs: rounded corners, north/south/east/west lines, etc.
1. Added two sample texts for testing: a more comprehensive box-drawing sample (see screenshot below), and [Kuhn's utf-8 demo](https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html). Agave renders the former almost perfectly, but compliance with the latter is more of a long-term goal.

**Further note:**

With the new release, hinting is now done by fontforge's autohint and autoinst, rather than by ttfautohint. The latter caused gaps to appear between box-drawing glyphs at small sizes.

**Screenshot:**  
TOP: windows notepad, size 11  
BOTTOM: linux emacs gui, similar size

![box](https://user-images.githubusercontent.com/15623001/87269141-94615280-c4cc-11ea-94e6-095f1be60441.png)

**Comment by traws0** [comment]
Hello @agarick,
I would like to report that v17 introduced some misaligments for me which were not present in v16. This is win10, notepad and happens with multiple font sizes.

![image](https://user-images.githubusercontent.com/7069042/87301925-ced7e900-c4e6-11ea-9cb1-5c8b1e7dbeb2.png)

**Comment by blobject** [comment]
Oh noes, I will look in to this later today.

I have so far been unable to reproduce this with windows 10 notepad, at any sizes, or with linux.

Perhaps I uploaded the wrong file. Would you be so kind as to try with the new ttf file (Agave-traws0.ttf) at https://github.com/agarick/agave/releases/tag/v17 ?

**Comment by traws0** [comment]
I tried the new  ttf file after removing the old font and rebooting and the issue persists for multiple font sizes. 

![image](https://user-images.githubusercontent.com/7069042/87323468-2f761e80-c505-11ea-8953-8cb1968df55c.png)

**Comment by blobject** [comment]
I'm sorry to have to ask you this, but I simply cannot reproduce the behavior on my side.

Could you please try the "-traws0.ttf" at https://github.com/agarick/agave/releases/tag/v17 again?

There probably will be gaps, but I am wondering if this new alignment issue also exists.

**Comment by traws0** [comment]
No problem. Here is the same text in the new relesase:

![image](https://user-images.githubusercontent.com/7069042/87473216-80663f80-c5f7-11ea-8700-531f2df16982.png)

**Comment by blobject** [comment]
Hopefully https://github.com/agarick/agave/commit/ddcc71f3e59fafe740f6d74dc8205f72038084dd ([release v18](https://github.com/agarick/agave/releases/tag/v18)) fixes this. @traws0 Please let me know if it does.

I have opted to forgo any hinting:
- fontforge's autohint/autoinst cause misalignment as seen in the latter part of this issue, and
- ttfautohint causes misrecognition of some box drawing glyphs (rounded corners) in linux

This will likely reopen https://github.com/agarick/agave/issues/9 so I will look into the hinting issue there.

**Comment by blobject** [comment]
[release v19](https://github.com/agarick/agave/releases/tag/v19) hopefully preserves good alignment behavior and also good hinting for some text editors on windows.

ttfautohint turns out to no longer misrecognise certain box drawing glyphs. Not sure why.

**Comment by traws0** [comment]
Awesome, it is perfect now. Thank you.
